let currentStep=1;
let autoSaveTimer=null,saveStatusTimer=null,toastTimer=null;
const AUTO_SAVE_DELAY=1500;
const STORAGE_KEY="consumerComplaintProductionV15";

let provinces=[],districts=[],subDistricts=[];
const PROVINCE_URL="https://raw.githubusercontent.com/kongvut/thai-province-data/refs/heads/master/api/latest/province.json";
const DISTRICT_URL="https://raw.githubusercontent.com/kongvut/thai-province-data/refs/heads/master/api/latest/district.json";
const SUB_DISTRICT_URL="https://raw.githubusercontent.com/kongvut/thai-province-data/refs/heads/master/api/latest/sub_district.json";

const evidenceTypes=[
"สำเนาบัตรประชาชน / บัตรข้าราชการ","สำเนาใบเสร็จรับเงิน","หลักฐานการชำระเงิน / การโอนเงิน","หลักฐานแจ้งความประจำวัน","เอกสารโฆษณา","ฉลากสินค้า","ภาพถ่ายสินค้า / ความเสียหาย","สำเนาสัญญา","หนังสือมอบอำนาจ","สำเนากรมธรรม์","สำเนาหนังสือเดินทาง","สำเนาบัญชีธนาคาร / Statement","สำเนาใบแจ้งหนี้","ใบรับซ่อม","หลักฐานการสนทนา","เลขที่คำสั่งซื้อ","เอกสารประกอบการร้องเรียนทั้งหมด","อื่น ๆ"];
const allowedExtensions=["pdf","jpg","jpeg","png","doc","docx"];
const maxFileSize=5*1024*1024;

function showToast(message){const t=document.getElementById("toast");t.textContent=message;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function startComplaint(){showForm();showStep(1)}
function continueDraft(){showForm();restoreDraft()}
function showForm(){document.getElementById("homePage").classList.remove("active-page");document.getElementById("formPage").classList.add("active-page");window.scrollTo({top:0})}
function goHome(){forceSaveNow();document.getElementById("formPage").classList.remove("active-page");document.getElementById("homePage").classList.add("active-page");window.scrollTo({top:0})}
function valueOf(id){const e=document.getElementById(id);return e?e.value.trim():""}
function checkedValues(name){return Array.from(document.querySelectorAll(`input[name="${name}"]:checked`)).map(i=>i.value)}
function selectedText(id){const e=document.getElementById(id);if(!e||!e.value)return "";return e.options[e.selectedIndex].textContent.trim()}
function setSaveStatus(text,type=""){const e=document.getElementById("saveStatus");e.textContent=text;e.className="save-status";if(type)e.classList.add(type)}
function scheduleAutoSave(){clearTimeout(autoSaveTimer);setSaveStatus("กำลังพิมพ์...","typing");autoSaveTimer=setTimeout(()=>saveDraft(),AUTO_SAVE_DELAY)}
function saveDraft(showMessage=false){clearTimeout(autoSaveTimer);setSaveStatus("กำลังบันทึก...","saving");try{localStorage.setItem(STORAGE_KEY,JSON.stringify(getDraftData()));updateContinueButton();setSaveStatus("บันทึกแล้ว ✓");clearTimeout(saveStatusTimer);saveStatusTimer=setTimeout(()=>setSaveStatus("บันทึกอัตโนมัติ: เปิด"),1600);if(showMessage)showToast("บันทึกแบบร่างเรียบร้อยแล้ว")}catch(error){console.error(error);setSaveStatus("บันทึกไม่สำเร็จ")}}
function forceSaveNow(){clearTimeout(autoSaveTimer);saveDraft()}
function getDraftData(){return{currentStep,name:valueOf("name"),category:valueOf("category"),incidentDate:valueOf("incidentDate"),problem:valueOf("problem"),problemImproved:document.getElementById("problem").dataset.improved||"",damage:valueOf("damage"),requestDetail:valueOf("requestDetail"),company:valueOf("company"),companyDetail:valueOf("companyDetail"),address:valueOf("address"),province:valueOf("province"),district:valueOf("district"),subDistrict:valueOf("subDistrict"),postcode:valueOf("postcode"),companyPhone:valueOf("companyPhone"),companyChannel:valueOf("companyChannel"),payment:checkedValues("payment"),request:checkedValues("request"),place:checkedValues("place")}}
async function loadThaiAddressData(){const s=document.getElementById("addressStatus");try{s.textContent="กำลังโหลดข้อมูลที่อยู่...";const r=await Promise.all([fetch(PROVINCE_URL),fetch(DISTRICT_URL),fetch(SUB_DISTRICT_URL)]);if(!r[0].ok||!r[1].ok||!r[2].ok)throw new Error("Address data error");provinces=await r[0].json();districts=await r[1].json();subDistricts=await r[2].json();createProvinceOptions();s.className="address-status success";s.textContent="ข้อมูลจังหวัดพร้อมใช้งาน ✓";return true}catch(error){console.error(error);s.className="address-status error";s.textContent="ไม่สามารถโหลดข้อมูลจังหวัดได้ กรุณาตรวจสอบอินเทอร์เน็ต";return false}}
function createProvinceOptions(){const s=document.getElementById("province");s.innerHTML='<option value="">-- เลือกจังหวัด --</option>';provinces.forEach(p=>{const o=document.createElement("option");o.value=String(p.id);o.textContent=p.name.th;s.appendChild(o)});s.disabled=false}
function provinceChanged(shouldSave=true){const pid=Number(valueOf("province")),d=document.getElementById("district"),sd=document.getElementById("subDistrict");d.innerHTML='<option value="">-- เลือกอำเภอ / เขต --</option>';sd.innerHTML='<option value="">-- กรุณาเลือกอำเภอก่อน --</option>';d.disabled=true;sd.disabled=true;document.getElementById("postcode").value="";if(!pid){if(shouldSave)saveDraft();return}districts.filter(i=>Number(i.province_id)===pid).forEach(i=>{const o=document.createElement("option");o.value=String(i.id);o.textContent=`${i.prefix?.th||""}${i.name.th}`;d.appendChild(o)});d.disabled=false;if(shouldSave)saveDraft()}
function districtChanged(shouldSave=true){const did=Number(valueOf("district")),s=document.getElementById("subDistrict");s.innerHTML='<option value="">-- เลือกตำบล / แขวง --</option>';s.disabled=true;document.getElementById("postcode").value="";if(!did){if(shouldSave)saveDraft();return}subDistricts.filter(i=>Number(i.district_id)===did).forEach(i=>{const o=document.createElement("option");o.value=String(i.id);o.textContent=`${i.prefix?.th||""}${i.name.th}`;s.appendChild(o)});s.disabled=false;if(shouldSave)saveDraft()}
function subDistrictChanged(shouldSave=true){const id=Number(valueOf("subDistrict")),p=document.getElementById("postcode"),s=document.getElementById("addressStatus");p.value="";if(!id){s.className="address-status";s.textContent="กรุณาเลือกตำบล / แขวง";return}const selected=subDistricts.find(i=>Number(i.id)===id);if(!selected)return;p.value=selected.zip_code?String(selected.zip_code):"";s.className="address-status success";s.textContent=`${selectedText("subDistrict")} • รหัสไปรษณีย์ ${p.value||"-"}`;if(shouldSave)saveDraft()}
function getFullAddress(){const parts=[];if(valueOf("address"))parts.push(valueOf("address"));if(selectedText("subDistrict"))parts.push(selectedText("subDistrict"));if(selectedText("district"))parts.push(selectedText("district"));if(selectedText("province"))parts.push("จังหวัด"+selectedText("province"));if(valueOf("postcode"))parts.push(valueOf("postcode"));return parts.join(" ")}
function createUploadFields(){const c=document.getElementById("uploadList");c.innerHTML="";evidenceTypes.forEach((type,index)=>{const card=document.createElement("div");card.className="upload-card";card.innerHTML=`<h3>${type}</h3><input type="file" id="file${index}" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onchange="validateFile(${index})"><div id="status${index}" class="file-status">ยังไม่ได้เลือกไฟล์</div>`;c.appendChild(card)})}
function validateFile(index){const input=document.getElementById(`file${index}`),status=document.getElementById(`status${index}`);if(!input.files.length){status.className="file-status";status.textContent="ยังไม่ได้เลือกไฟล์";return}const file=input.files[0],ext=file.name.split(".").pop().toLowerCase();if(!allowedExtensions.includes(ext)){status.className="file-status file-error";status.textContent="ไม่รองรับไฟล์ประเภทนี้";input.value="";return}if(file.size>maxFileSize){status.className="file-status file-error";status.textContent="ไฟล์มีขนาดเกิน 5 MB";input.value="";return}status.className="file-status file-ok";status.textContent=`พร้อมใช้งาน ✓ ${file.name}`}
function getSelectedFiles(){const files=[];evidenceTypes.forEach((type,index)=>{const input=document.getElementById(`file${index}`);if(input&&input.files&&input.files.length){files.push({type,name:input.files[0].name})}});return files}
function improveComplaint(){const f=document.getElementById("problem"),text=f.value.trim();if(!text){showToast("กรุณาพิมพ์รายละเอียดปัญหาก่อน");return}if(f.dataset.improved==="true"){showToast("ข้อความนี้ถูกเรียบเรียงแล้ว สามารถแก้ไขเพิ่มเติมได้เลย");return}let result=`ข้าพเจ้าประสบปัญหาเกี่ยวกับ ${valueOf("category")||"สินค้า หรือบริการ"} โดยมีรายละเอียดดังนี้\n\n${text}`;if(valueOf("damage"))result+=`\n\nจากเหตุการณ์ดังกล่าว ข้าพเจ้าได้รับความเสียหายคิดเป็นมูลค่าประมาณ ${Number(valueOf("damage")).toLocaleString("th-TH")} บาท`;const req=checkedValues("request");if(req.length)result+=`\n\nความประสงค์ของข้าพเจ้า ได้แก่ ${req.join(", ")}`;result+=`\n\nจึงขอให้หน่วยงานที่เกี่ยวข้องตรวจสอบข้อเท็จจริง และพิจารณาให้ความช่วยเหลือตามความเหมาะสม`;f.value=result;f.dataset.improved="true";forceSaveNow();showToast("เรียบเรียงข้อความแล้ว กรุณาตรวจสอบก่อนใช้งาน")}
function nextStep(step){if(step===1){if(!valueOf("name")){showToast("กรุณากรอกชื่อผู้ร้องเรียน");return}if(!valueOf("category")){showToast("กรุณาเลือกประเภทปัญหา");return}if(!valueOf("problem")){showToast("กรุณากรอกรายละเอียดเรื่องร้องเรียน");return}}if(step===2&&!valueOf("company")){showToast("กรุณากรอกชื่อผู้ถูกร้องเรียน");return}if(step===3)createFinalReview();showStep(step+1);forceSaveNow()}
function previousStep(step){showStep(step-1);forceSaveNow()}
function showStep(step){currentStep=step;document.querySelectorAll(".step").forEach(i=>i.classList.remove("active"));document.getElementById(`step${step}`).classList.add("active");updateProgress();if(step===4)createFinalReview();window.scrollTo({top:0,behavior:"smooth"})}
function updateProgress(){for(let i=1;i<=4;i++){const item=document.getElementById(`progress${i}`);item.classList.remove("active","completed");if(i===currentStep)item.classList.add("active");if(i<currentStep)item.classList.add("completed")}}
function calculateReadiness(){const files=getSelectedFiles();const checks=[{name:"ชื่อผู้ร้องเรียน",passed:Boolean(valueOf("name"))},{name:"ประเภทปัญหา",passed:Boolean(valueOf("category"))},{name:"วันที่เกิดเหตุ",passed:Boolean(valueOf("incidentDate"))},{name:"รายละเอียดเหตุการณ์",passed:valueOf("problem").length>=20},{name:"มูลค่าความเสียหาย",passed:Boolean(valueOf("damage"))},{name:"วิธีการชำระเงิน",passed:checkedValues("payment").length>0},{name:"ความประสงค์",passed:checkedValues("request").length>0},{name:"ชื่อผู้ถูกร้องเรียน",passed:Boolean(valueOf("company"))},{name:"ข้อมูลที่อยู่ผู้ถูกร้อง",passed:Boolean(valueOf("address")||(valueOf("province")&&valueOf("district")&&valueOf("subDistrict")))},{name:"หลักฐานประกอบ",passed:files.length>0}];const passed=checks.filter(i=>i.passed).length;return{score:Math.round((passed/checks.length)*100),checks}}
function createFinalReview(){const result=calculateReadiness();document.getElementById("readinessScore").textContent=`${result.score}%`;document.getElementById("scoreBar").style.width=`${result.score}%`;document.getElementById("readinessStatus").textContent=result.score>=90?"พร้อมมาก":result.score>=70?"เกือบพร้อม":result.score>=50?"ควรตรวจเพิ่ม":"ข้อมูลยังไม่ครบ";document.getElementById("readinessChecklist").innerHTML=result.checks.map(i=>`<div class="check-item ${i.passed?"ok":"missing"}">${i.passed?"✓":"!"} ${escapeHTML(i.name)}</div>`).join("");const missing=result.checks.filter(i=>!i.passed),w=document.getElementById("missingWarning");if(missing.length){w.classList.add("show");w.innerHTML=`<strong>แนะนำให้ตรวจเพิ่มเติม</strong><br><br>${missing.map(i=>`• ${escapeHTML(i.name)}`).join("<br>")}`}else{w.classList.remove("show");w.innerHTML=""}createSummary()}
function createSummary(){const files=getSelectedFiles(),fileText=files.length?files.map(i=>`${i.type}: ${i.name}`).join("\n"):"ยังไม่ได้เลือกไฟล์",damage=valueOf("damage")?Number(valueOf("damage")).toLocaleString("th-TH")+" บาท":"ไม่ระบุ";document.getElementById("summaryBox").innerHTML=`<div class="summary-card"><h3>ข้อมูลเรื่องร้องเรียน</h3>${summaryRow("ชื่อผู้ร้องเรียน",valueOf("name"))}${summaryRow("ประเภทปัญหา",valueOf("category"))}${summaryRow("วันที่เกิดเหตุ",valueOf("incidentDate")||"ไม่ระบุ")}${summaryRow("รายละเอียด",valueOf("problem"))}${summaryRow("มูลค่าความเสียหาย",damage)}${summaryRow("การชำระเงิน",checkedValues("payment").join(", ")||"ไม่ระบุ")}${summaryRow("ความประสงค์",checkedValues("request").join(", ")||"ไม่ระบุ")}${summaryRow("รายละเอียดความประสงค์",valueOf("requestDetail")||"ไม่ระบุ")}</div><div class="summary-card"><h3>ข้อมูลผู้ถูกร้องเรียน</h3>${summaryRow("ชื่อ",valueOf("company"))}${summaryRow("รายละเอียดเพิ่มเติม",valueOf("companyDetail")||"ไม่ระบุ")}${summaryRow("ที่อยู่",getFullAddress()||"ไม่ระบุ")}${summaryRow("โทรศัพท์",valueOf("companyPhone")||"ไม่ระบุ")}${summaryRow("ช่องทางออนไลน์",valueOf("companyChannel")||"ไม่ระบุ")}${summaryRow("สถานที่ซื้อหรือใช้บริการ",checkedValues("place").join(", ")||"ไม่ระบุ")}</div><div class="summary-card"><h3>หลักฐาน</h3>${summaryRow("ไฟล์ที่เตรียมไว้",fileText)}</div>`}
function summaryRow(title,value){return `<div class="summary-row"><div class="summary-title">${escapeHTML(title)}</div><div class="summary-value">${escapeHTML(value||"ไม่ระบุ")}</div></div>`}
function escapeHTML(text){return String(text).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
async function copyText(text,message="คัดลอกเรียบร้อยแล้ว"){if(!text||!text.trim()){showToast("ยังไม่มีข้อมูลในส่วนนี้");return}try{await navigator.clipboard.writeText(text);showToast(message)}catch{const t=document.createElement("textarea");t.value=text;t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.focus();t.select();document.execCommand("copy");t.remove();showToast(message)}}
function copyField(id){copyText(valueOf(id))}
function copyPayment(){copyText(checkedValues("payment").join(", "),"คัดลอกวิธีการชำระเงินแล้ว")}
function copyRequest(){copyText(checkedValues("request").join(", "),"คัดลอกความประสงค์แล้ว")}
function copyFullAddress(){copyText(getFullAddress(),"คัดลอกที่อยู่แล้ว")}
function buildCopyText(){const damage=valueOf("damage")?Number(valueOf("damage")).toLocaleString("th-TH")+" บาท":"ไม่ระบุ";return `ข้อมูลเตรียมยื่นเรื่องร้องเรียน\n\nชื่อผู้ร้องเรียน:\n${valueOf("name")}\n\nประเภทปัญหา:\n${valueOf("category")}\n\nวันที่เกิดเหตุ:\n${valueOf("incidentDate")||"ไม่ระบุ"}\n\nรายละเอียดเรื่องร้องเรียน:\n${valueOf("problem")}\n\nมูลค่าความเสียหาย:\n${damage}\n\nการชำระเงิน:\n${checkedValues("payment").join(", ")||"ไม่ระบุ"}\n\nความประสงค์:\n${checkedValues("request").join(", ")||"ไม่ระบุ"}\n\nรายละเอียดความประสงค์เพิ่มเติม:\n${valueOf("requestDetail")||"ไม่ระบุ"}\n\nชื่อบริษัท / ร้านค้า / หน่วยงาน:\n${valueOf("company")}\n\nรายละเอียดผู้ถูกร้องเรียน:\n${valueOf("companyDetail")||"ไม่ระบุ"}\n\nที่อยู่:\n${getFullAddress()||"ไม่ระบุ"}\n\nเบอร์โทรศัพท์:\n${valueOf("companyPhone")||"ไม่ระบุ"}\n\nช่องทางออนไลน์:\n${valueOf("companyChannel")||"ไม่ระบุ"}\n\nสถานที่ซื้อหรือใช้บริการ:\n${checkedValues("place").join(", ")||"ไม่ระบุ"}\n\nหมายเหตุ:\nข้อมูลนี้จัดทำผ่านเครื่องมือช่วยเตรียมข้อมูลคำร้อง\nโปรดตรวจสอบข้อเท็จจริงก่อนนำไปยื่นต่อหน่วยงาน`}
function copySummary(){copyText(buildCopyText(),"คัดลอกข้อมูลทั้งหมดแล้ว")}
function openOCPB(){window.open("https://complaint.ocpb.go.th","_blank","noopener")}
function restoreDraft(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw){showToast("ยังไม่มีแบบร่างที่บันทึกไว้");showStep(1);return}try{const data=JSON.parse(raw),fields=["name","category","incidentDate","problem","damage","requestDetail","company","companyDetail","address","companyPhone","companyChannel"];fields.forEach(id=>{const f=document.getElementById(id);if(f&&data[id]!==undefined)f.value=data[id]||""});document.getElementById("problem").dataset.improved=data.problemImproved||"";restoreChecks("payment",data.payment);restoreChecks("request",data.request);restoreChecks("place",data.place);restoreAddress(data);const savedStep=Number(data.currentStep);showStep(savedStep>=1&&savedStep<=4?savedStep:1);setSaveStatus("กู้คืนแบบร่างแล้ว ✓");showToast("เปิดแบบร่างล่าสุดแล้ว")}catch(error){console.error(error);showToast("ไม่สามารถเปิดแบบร่างได้")}}
function restoreAddress(data){if(!data.province)return;document.getElementById("province").value=data.province;provinceChanged(false);if(data.district){document.getElementById("district").value=data.district;districtChanged(false)}if(data.subDistrict){document.getElementById("subDistrict").value=data.subDistrict;subDistrictChanged(false)}}
function restoreChecks(name,values){if(!Array.isArray(values))return;document.querySelectorAll(`input[name="${name}"]`).forEach(i=>i.checked=values.includes(i.value))}
function enableAutoSave(){document.querySelectorAll('input[type="text"], input[type="tel"], input[type="number"], input[type="date"], textarea').forEach(e=>e.addEventListener("input",()=>{if(e.id==="problem")e.dataset.improved="false";scheduleAutoSave()}));document.querySelectorAll('input[type="checkbox"]').forEach(e=>e.addEventListener("change",()=>saveDraft()));document.querySelectorAll("select").forEach(e=>{if(!["province","district","subDistrict"].includes(e.id))e.addEventListener("change",()=>saveDraft())})}
function updateContinueButton(){const b=document.getElementById("continueButton"),hasDraft=Boolean(localStorage.getItem(STORAGE_KEY));b.textContent=hasDraft?"เปิดแบบร่างล่าสุด":"ยังไม่มีแบบร่าง"}
function clearEverything(){if(!confirm("ต้องการล้างข้อมูลแบบร่างทั้งหมดใช่หรือไม่?"))return;clearTimeout(autoSaveTimer);localStorage.removeItem(STORAGE_KEY);location.reload()}
async function initializeApp(){createUploadFields();enableAutoSave();updateContinueButton();await loadThaiAddressData()}
initializeApp();
